### ISSUE TITLE
Application loads in popup window with Okta login

### ISSUE THREAD

**Issue by maxlapides** [auth0/lock#858] opened 2017-02-06 19:00 UTC
*Steps to reproduce*
1. Set `auth.redirect` to false
2. Log in to application using an Okta SSO account
3. Application loads in authentication popup window instead of main window

**Comment by hzalaz** [comment] 2017-02-06 19:23
@maxlapides can you show us, in a snippet, how you setup Lock?.

**Comment by maxlapides** [comment] 2017-02-06 19:24
```
new Auth0Lock(
    res.clientId,
    res.domain,
    {
        auth: {
            redirect     : false,
            sso          : true,
            responseType : 'token',
            params       : { scope: 'openid email' }
        },
        languageDictionary : {
            lastLoginInstructions : 'Last time you signed in with...',
            notYourAccountAction  : 'Use a different account',
            usernameOrEmailInputPlaceholder : 'Email / Username',
            passwordInputPlaceholder: 'Password',
            loginLabel : 'Sign In',
            loginSubmitLabel : 'Sign In'
        },
        theme : {
            logo : null
        },
        allowForgotPassword : false,
        closable            : false,
        autoclose           : true,
        allowSignUp         : false,
        avatar              : null
    }
)
```

**Comment by hzalaz** [comment] 2017-02-06 19:25
thanks @maxlapides, latest version?

**Comment by maxlapides** [comment] 2017-02-06 19:26
@hzalaz yes!

**Comment by hzalaz** [comment] 2017-02-06 19:26
ok will check it, Okta is set up as saml connection right @maxlapides ?

**Comment by maxlapides** [comment] 2017-02-06 19:29
@hzalaz yeah, it's set up as SAMLP

**Comment by hzalaz** [comment] 2017-02-06 22:21
@maxlapides we tried to reproduce with a non-okta saml connection and the popup closes perfectly.

Can you send us via https://support.auth0.com a HAR, or whatever you can collect, of the requests made in the popup so we can know at one point it ends up in your application instead of the callback url that closes the popup?

You can post the ticket number here so we can check it out.

Also if you can provide us a site to test with credentials it will really help us.

**Comment by maxlapides** [comment] 2017-02-06 22:25
@hzalaz Can you try to reproduce it with an Okta SAML connection? I believe the issue is specific to Okta, which is used by many of our clients. If that's not successful, please let me know and we can move onto next steps. Do you also want me to open a support ticket?

**Comment by hzalaz** [comment] 2017-02-06 22:41
@maxlapides we don't have an Okta environment to test this so it will take some time to set this up and there is also the chance that some Okta configuration triggers the issue. 
If you can provide us with a testing account this will make us troubleshoot this faster

I'd recommend submitting a support ticket whatever you decide, with as much information as you can provide, since this might involve other components besides Lock

**Comment by maxlapides** [comment] 2017-02-07 18:12
@hzalaz unfortunately I don't have any time to set this up right now. we're just going to use redirect mode for the time being, but I do believe this is still an open issue.

**Comment by hzalaz** [comment] 2017-02-08 20:16
@maxlapides we tried with an Okta account as a SAML connection with popup mode and everything works with this setup https://gist.github.com/hzalaz/287fcb07628b31b0e476be7449484650.

Please send us a ticket with the necessary steps and data to reproduce it, in the meantime will close this one (feel free to reopen if you can share more info here)

**Closed by hzalaz** 2017-02-08 20:16 UTC
