### ISSUE TITLE
Problems when minifying Lock concatenated with other files

### ISSUE THREAD

**Issue by mgonto** [auth0/lock#94] opened 2014-12-17 17:24 UTC
Please refer to https://github.com/auth0/auth0-angular/issues/96

**Comment by mgonto** [comment] 2015-01-05 16:16
Related also to https://github.com/auth0/auth0-angular/issues/121

**Comment by mgonto** [comment] 2015-01-05 17:56
Hey @kevinob11,

we're working on tackling this issue. Can you provide us a sample project to reproduce it?

Thanks!

**Comment by kevinob11** [comment] 2015-01-05 18:32
Yep, I'll need to pull it out of my private repo. I'll be working on that Wednesday, I'll try to get it to you then!

**Comment by mgonto** [comment] 2015-01-05 21:16
Awesome thanks for the help :D

**Comment by johnstontrav** [comment] 2015-01-05 23:02
Hey @mgonto,

Here is a seed project:

https://bitbucket.org/Johnstontrav/auth0-seed-issue-94

It is built with https://github.com/Swiip/generator-gulp-angular

Once cloned, run steps:

1. npm install && bower install

2. edit file: src/app/index.js

3. update the Auth0 settings.

4. gulp serve - firebug should report "Client configuration loaded"

5. gulp serve:dist - should report the error.

Let me know if I can help further.

**Comment by kevinob11** [comment] 2015-01-05 23:38
That looks right to me, generator-gulp-angular is the exact generator I used, though I think you will need to run gulp:build so you have the dist folder before running gulp serve:dist.

**Comment by mgonto** [comment] 2015-01-06 02:38
Awesome thanks for the seed project reproducing it. @cristiandouce can you now check this out :)?

**Comment by cristiandouce** [comment] 2015-01-06 17:06
After debugging this a while, I've come with the problem... not yet the solution though.

Using chrome dev tools I've found this:

![image](https://cloud.githubusercontent.com/assets/367429/5632324/90ed563a-95ac-11e4-967a-f1a81e58dcac.png)

Which, as we can see... `auth0-angular` isn't parsing the variables according to Auth0Lock spec.

This is because of some resolve `auth0-angular` does on the constructor name, to detect whether you are using Auth0Lock or Auth0.js.

This check on the `Constructor` name, is broken once mangling and minifying stuff together, since the uglify tool does not know that Auth0Lock should be defined globally so auth0-angular could resolve how to parse the initialization variables.

That's why when `mangle: false` everything works as expected!

@mgonto will continue the follow of this in auth0/auth0-angular#96 and auth0/auth0-angular#121

The temporary solution to this would be either load the `auth0-lock.min.js` script outside the minifying or providing the `mangle: false` setup to the uglify tool.

This will also be added to the `auth0-angular` Readme as a common error.

**Comment by cristiandouce** [comment] 2015-01-06 18:22
Closing now, since it's confirmed a bug in how `auth0-angular` resolves `fnName`s for Constructors.

![image](https://cloud.githubusercontent.com/assets/367429/5633559/8d418db6-95b7-11e4-9bde-d40b05ceb7c0.png)

Here, in Chrome's devtools console you can type:
```
r === Auth0Lock
// > true
```

But, the `fnName` is `r` which is not equal to `Auth0Lock` :dart:

**Comment by mgonto** [comment] 2015-01-06 19:00
At all, it has been fixed with version `4.0.1` of `auth0-angular` :).

I've also submited a PR to the sample proving it's working now :).

https://bitbucket.org/Johnstontrav/auth0-seed-issue-94/pull-request/1/fix-with-auth0-angular-401

Cheers!

**Comment by kevinob11** [comment] 2015-01-06 20:11
Should 4.0.1 be v4.0.1 or am I missing something in the tag naming convention?

**Comment by johnstontrav** [comment] 2015-01-07 00:42
@cristiandouce thanks for the fix.  I possible have another issue, it seems the minify dist fails to pass the authParams.

auth.signin({
            showIcon: false,
            closable: false,
            disableSignupAction: true,
            authParams: {"app_id": "blah"}
        }, function (profile, token) { .....})

I have a custom Rule like this:

function (user, context, callback) {

    var app_id = context.request.body && context.request.body.app_id;

    ....
}

Note this code works perfectly via:  gulp serve    but fails to receive the app_id on gulp serve:dist

**Comment by cristiandouce** [comment] 2015-01-07 00:49
@johnstontrav how do you notice the failure? is there some error message? Can you print fully or partially the content of `the context.request.body`?

**Comment by johnstontrav** [comment] 2015-01-07 01:09
@cristiandouce I wasn't sure of the best way to do that, but i have tried this:

 return callback(new UnauthorizedError('No access - '+JSON.stringify(context.request.body)));

No Minify
------------
Whilst this works with correct data, the screenshot shows error when bad data is passed via authParams.

![screen shot 2015-01-07 at 12 03 57 pm](https://cloud.githubusercontent.com/assets/7200330/5639144/7e165f7a-9665-11e4-9123-77220a48dbf3.png)


With Minify
------------
The page is refresh and not trapped by promise, the Auth0 return is in the url.

}, function (error) {
            console.log("There was an error logging in", error);
        });

![screen shot 2015-01-07 at 12 04 49 pm](https://cloud.githubusercontent.com/assets/7200330/5639161/b44fc464-9665-11e4-8008-d2df436708d0.png)

**Comment by cristiandouce** [comment] 2015-01-07 02:17
@mgonto Any clue why the promise may not be recognized?

If there is a function, Auth0Lock should post the request and wait for reponse, and then call it.

**Comment by johnstontrav** [comment] 2015-01-08 22:33
@mgonto @cristiandouce hey guys, any news on the minify authParams issue?

**Comment by mgonto** [comment] 2015-01-09 14:22
> Should 4.0.1 be v4.0.1 or am I missing something in the tag naming convention?

@kevinob11 it's the same. I used to make it with npm patch but I don't like the `v` to be honest :P so I changed it. However, both work with bower and npm :).

**Comment by mgonto** [comment] 2015-01-09 14:25
@johnkors  Angular version doesn't  use promises either, it just gets the callback from Lock and passes it through. However, when you're sending `authParams` they should part of the Query String,not the body of the request. Have you checked getting it from `context.request.query`?

Can you again put this in a sample repository so that I can take a look?

Thanks!

**Comment by johnkors** [comment] 2015-01-10 11:48
Guessing that comment was for another John :) @johnstontrav

**Comment by johnstontrav** [comment] 2015-01-11 23:32
@cristiandouce @mgonto het guys im trying to update the demo code to reproduce this issue, but I am having some more login issues.  I have emailed support queue with details as it may not be a public related issue.

**Comment by johnstontrav** [comment] 2015-01-12 00:39
@mgonto your correct with "query".  i can access via:

app_id = context.request.query && context.request.query.app_id;

I was also missing this in my code:

jwtInterceptorProvider.tokenGetter = ['store', function (store) {
            return store.get('token');
        }];

It now appears to be working via the minify.  Yay!

**Comment by cristiandouce** [comment] 2015-01-12 01:59
@johnstontrav glad you could solve this out!

**Closed by cristiandouce** 2015-01-12 01:59 UTC
Labels: bug
