### ISSUE TITLE
loginAfterSignUp false not working when using custom Database script

### ISSUE THREAD

**Issue by nnsm3** [auth0/lock#1943] opened 2020-11-07 09:12 UTC
### Describe the problem

using `loginAfterSignUp:false` not working as expected with custom DB script for login and signup

### What was the expected behavior?

should not auto-login if set to false 

### Environment

> Please provide the following:

- **Version of Lock used:** 11.27
- **Which browsers have you tested in?** chrome

**Comment by stevehobbsdev** [comment] 2020-12-02 11:45
@nnsm3 Apologies for the delay here. Let me look into this and come back to you.

**Comment by stevehobbsdev** [comment] 2021-01-06 17:28
@nnsm3 Hi again, apologies for the delay. I've finally managed to get some time to set up a custom database to try this out and unfortunately I cannot reproduce what you're seeing.

Let me know if you are still having issues. If so, can you try and reproduce it using the Lock playground using the following steps:

1. Clone this repo (requires Node 10 currently) and `npm install` or `yarn`
2. Switch to the `custom-db-signup` branch
3. Run `yarn dev`
4. Open https://localhost:3000/support
5. Login with email `test@test.com` and any password that matches the criteria
6. Confirm that you can see the "Thanks for signing up" confirmation dialog, rather than being logged in

![image](https://user-images.githubusercontent.com/766403/103800653-930c7f00-5044-11eb-848a-d9151b6b4dd7.png)

This branch is set up with a tenant that uses a custom database to sign in so should be representative of what you're seeing. It's also [configured not to login after signup](https://github.com/auth0/lock/blob/custom-db-signup/support/index.html#L131).

Please let me know if you hit any issues or are seeing something different.

**Comment by stevehobbsdev** [comment] 2021-01-13 16:26
Closing this for now but if you manage to identify anything further that would allow us to investigate more, I'll be happy to reopen.

**Closed by stevehobbsdev** 2021-01-13 16:26 UTC
Labels: bug report, cannot repro
