### ISSUE TITLE
login button is not visible in lock widget on the mobile version after redirect to hosted login page

### ISSUE THREAD

**Issue by alexanderPastornicky** [auth0/lock#1223] opened 2018-01-11 22:05 UTC
Android 7, latest Chrome, default hosted login template

![screenshot_2018-01-11-22-56-11-230_com android chrome](https://user-images.githubusercontent.com/2699816/34849859-175bc7a2-f724-11e7-8ca6-220b70f82e65.png)

**Comment by adrogon** [comment] 2018-04-18 10:45
This affects Chrome on Android as well as Safari on iPhone, so most likely any browser any device.

A screen whose height is smaller than ~600px won't handle a Lock widget with some social connections.
Please also consider the error messages that can span over several lines.

The responsiveness needs to be improved, with components height and locations changed based on the available viewport.
Or, more simply, being able to scroll.

Here is an example of what we do to circumvent the issue (SCSS):

```SCSS
@media screen and (max-height: 580px) {
  .auth0-lock-header {
    height: 46px !important;
    
    .auth0-lock-header-logo {
      display: inline !important;
      height: 24px !important;
      margin-bottom: 0 !important;
      vertical-align: text-bottom !important;
    }

    .auth0-lock-name {
      display: inline !important;
      font-size: inherit !important;
      line-height: inherit !important;
    }
  }
}
```

**Comment by alexturc** [comment] 2018-10-24 17:20
When the viewport is small and an error message is presented, the Log In button is pushed down and the user needs to scroll, even if enough space would be available to fit all the information.

This happens at least on Chrome / Windows, but other browsers might be affected.

![image](https://user-images.githubusercontent.com/1728388/47448883-0d0f0100-d776-11e8-8b32-e8378a2459ca.png)

**Comment by luisrudge** [comment] 2018-10-25 16:39
duplicate of https://github.com/auth0/lock/issues/1474

**Closed by luisrudge** 2018-10-25 16:39 UTC
Labels: design
