### ISSUE TITLE
Auth0-lock is not working with requirejs

### ISSUE THREAD

**Issue by mlhch** [auth0/lock#95] opened 2014-12-18 08:28 UTC
Hi, obviously it is better to load auth0-lock.min.js(595k) dynamically when needed other than integrate it in SPA's index.html, so I'd like to get requirejs involved, then issues come:

Debug env: .../bower_components/auth0-lock/build/auth0-lock.js in Chrome

Error 1:
```
Uncaught Error: Mismatched anonymous define() module: function () {
            return md5;
        }
```
This is because below context wants to use the md5 function
```
var md5 = require('blueimp-md5').md5;
...
return 'https://www.gravatar.com/avatar/' + md5(parsedEmail) + '?d=404';
```
But since I used requirejs to load auth0-lock.js, the 'if' condition below is true, so bug appears:
```
    if (typeof define === 'function' && define.amd) {
        define(function () {
            return md5;
        });
    } else {
        $.md5 = md5;
    }
```

Error 2:
```
Uncaught TypeError: object is not a function
```
This is because below lines want to use 'sizzle', and expect it is a function
```
var sizzle       = require('sizzle');
...
module.exports = function (selector, root) {
  if ('string' === typeof selector) {
    return bonzo(sizzle((selector || ''), root));
  }

  return bonzo(selector);
};
```
But the same situation happens because of requirejs, the 'if' condition below becomes true and Sizzle was not exported correctly.
```
if ( typeof define === "function" && define.amd ) {
	define(function() { return Sizzle; });
// Sizzle requires that there be a global window in Common-JS like environments
} else if ( typeof module !== "undefined" && module.exports ) {
	module.exports = Sizzle;
} else {
	window.Sizzle = Sizzle;
}
```

I compared auth0-lock and auth0-widget, and found there is no modules "md5" and "sizzle" involved in the latter. So I think I've made the cause and effect clear.

PLEASE fix this ASAP and be careful about similar issues!

**Comment by pose** [comment] 2015-02-19 14:55
@mlhch Can you provide a working example that could help us go through your build process? A github repo with a Makefile or Gulpfile or Grunfile or anything will do. Thanks!

**Comment by rtucker88** [comment] 2015-02-25 18:48
I have the same issue using Webpack. I'll try to get a minimal test-case going for you.

**Comment by pose** [comment] 2015-02-25 18:50
@rtucker88 Awesome, thanks!

**Comment by rtucker88** [comment] 2015-02-25 19:18
Here's a minimal test-case showing the error. If you have any questions please let me know! https://github.com/rtucker88/auth0-md5-bug

**Comment by rtucker88** [comment] 2015-02-28 19:49
I came up with a potential fix, but I don't think it's the cleanest solution.

On line 23 of lib/gravatar/index.js add the following:

if(!md5) {
  md5 = require('blueimp-md5');
}

**Comment by cristiandouce** [comment] 2015-05-19 17:58
Please review this by using the new `7.5.4` version. @jfromaniello implemented a fix for this kind of bugs.

Reopen if still an issue.

**Comment by djwait** [comment] 2015-05-28 19:06
We use Auth0 in our iOS app and are now integrating it into our node/javascript/React app. We use webpack and I've been able to get it to load but couldn't get it working without using the line "23 of lib/gravatar/index.js" fix suggested by @rtucker88 . I'm using 7.5.4 so I think you may need to reopen this issue.

**Comment by cristiandouce** [comment] 2015-05-28 19:32
@djwait would you have a repro seed that we could use to debug the issue?
How are you requiring/initializing the app? are you using the build file?

Thanks!

**Comment by cristiandouce** [comment] 2015-05-28 19:34
@djwait also take a look at this issue:  #172 

and the seed project using requirejs: https://github.com/afgallo/auth0lock-requirejs by @afgallo

**Comment by djwait** [comment] 2015-05-28 19:50
Thanks. I'll take a look at these. I’m actually not using RequireJS. We’re using webpack to pull all the modules together for the browser. We use React and Fluxible. I’m not really familiar with RequireJS but I found this issue describes the problem I’m seeing. It’s got to do with the URL generation in the gravatar/index.js not finding the md5() function.

Here's the error from javascript console:

![screen shot 2015-05-28 at 3 48 58 pm](https://cloud.githubusercontent.com/assets/100485/7869483/1e2f241a-0551-11e5-8a78-ab4fd88d5bf2.png)

**Comment by cristiandouce** [comment] 2015-05-28 19:55
@djwait still, could you provide with a seed project hat reproduces the error?

For example, that reference to `gravatar/index.js` should never appear if you are using the `build/lock.js` on requires. Are you requiring that, or `standalone.js` ?

**Comment by djwait** [comment] 2015-05-28 19:57
I understand you need a reproducible case. I'll see what I can do to provide a simple example of the issue. Thanks.

**Comment by cristiandouce** [comment] 2015-05-28 20:01
@djwait you too for understanding! :grinning:

**Comment by djwait** [comment] 2015-05-29 14:43
@cristiandouce I've setup a stripped down copy of a Yahoo! example that includes my approach to integrating auth0. Their example demonstrates the architecture we're trying to follow. A lot of this is new to me and Javascript isn't my native language so I'm guessing I've done something wrong. Could you take a look at it? If you clone my 'fluxible-auth0-demo' repository you should be able to:

1. do an 'npm install' from the root of the repo
2. cd into 'react-router' and edit components/Application.jsx to add your auth0 test keys
3. run 'npm run dev'.

Once you've done that you should just go to the app in your browser and click on 'Sign In'. If you get the login box then login and watch your javascript console. You may need to go back to the page and click sign in again but you should see an uncaught exception saying that 'md5' isn't a function.

Here's the repo - https://github.com/djwait/fluxible-auth0-demo.git

**Comment by cristiandouce** [comment] 2015-05-29 17:12
#### Booted on `http://localhost:3000` with install and run instructions

![image](https://cloud.githubusercontent.com/assets/367429/7885714/e20d934e-05fb-11e5-9892-0ceb4503e4fc.png)

The error appears when it tries to async load the blueimp-md5 module using requirejs syntax (I guess) instead of commonjs I believe (since webpack supports both ways).

I'd recommend to use a built `external` Auth0Lock instead of attempting to load on demand from the code. Perhaps adding another grunt-task that bulds lock to a path and then use the externals config from webpack to load that.

@djwait what do you think?

**Comment by djwait** [comment] 2015-05-29 17:20
Just took a quick look at the webpack docs and it sounds like a good idea. Like I said, I'm not a webpack expert but looks like I'll become one! ;-)

I'll try that approach and let you know how it goes. Thanks for the assistance!

**Comment by cristiandouce** [comment] 2015-05-29 17:22
If we get it working, it would be also a good doc entry to add to https://github.com/auth0/docs :wink:

**Comment by djwait** [comment] 2015-06-01 14:26
@cristiandouce I haven't had time to really dive into this yet. On our real app I actually changed the config of the login screen to turn off gravatar, sso, and rememberLastLogin. That's the config we'll be running with and with that arrangement everything works fine using the standard 7.5.4 package.

I may look at this if I run into spare time but don't count on it. I'll leave it up to you as to whether you want to fix this or not.

**Comment by cristiandouce** [comment] 2015-06-01 14:27
@djwait we are already checking on it. We will keep you posted! Thanks!

**Comment by cristiandouce** [comment] 2015-06-02 02:07
@djwait we finally ended up implementing the fix @rtucker88 proposed a time ago.

Could you check that it's working now with the latest `auth0-lock@7.5.5`?

auth0/lock#175

**Comment by djwait** [comment] 2015-06-02 11:23
@cristiandouce I'll check it out as soon as I can. Have a minor deadline today but should be able to get to it in the next couple of days worst case.

**Comment by cristiandouce** [comment] 2015-06-03 15:15
Hey @djwait I'm closing this for now. Feel free to ping back if it doesn't work for you. We have also made it work in a [webpack example](https://github.com/auth0/lock/tree/master/examples/webpack).

Thanks!

**Closed by cristiandouce** 2015-06-03 15:15 UTC
Labels: bug
