### ISSUE TITLE
React reports an error with QuickAuthPane

### ISSUE THREAD

**Issue by pselle** [auth0/lock#607] opened 2016-09-14 15:11 UTC
- [x] Code snippet or sample project that reproduces the bug

`warning.js:44 Warning: You are manually calling a React.PropTypes validation function for the`alternativeClickHandler`prop on`QuickAuthPane`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.`
- [ ] Screenshots when appropriate
- [x] Lock version
  _10.0.1_
- [x] Browser & OS
  _Chrome, OS X_

I'm seeing this error in React; I can remove the validation function in a PR, but I'm not sure what you all prefer to do.

**Comment by hzalaz** [comment] 2016-09-14 21:13
@pselle did you try with latest Lock?

**Comment by pselle** [comment] 2016-09-19 13:34
@hzalaz I will update, but I see in the 10.2.2 release tree that `alternativeClickHandler` is still using a custom PropTypes validation function.

**Comment by glena** [comment] 2016-10-18 14:55
@pselle I am not able to reproduce that warning with the latest version of lock, in fact, checking the document about the deprecation and upgrade path provided in the warning you pasted, the suggested solution to handle this kind of validations is what we are doing (check the latest section here https://facebook.github.io/react/warnings/dont-call-proptypes.html#fixing-the-false-positive-in-third-party-proptypes and compare to https://github.com/auth0/lock/blob/v10.2.2/src/ui/pane/quick_auth_pane.jsx#L48-L52).

If you upgrade to lock `10.4` do you still see the warning?
Can you also add an example on how are you configuring lock, which kind of connection and when does it show the warning (is it when it shows the `Last time you logged in with` screen?)?

Thank you

**Comment by hzalaz** [comment] 2016-12-15 22:12
Closing this one, please reopen the issue with more info

**Closed by hzalaz** 2016-12-15 22:12 UTC
Labels: P3: Important, S2: Inconvenient, v10
