### ISSUE TITLE
Lock 10.11.0 - authentication event emitted on authorization dialog cancel

### ISSUE THREAD

**Issue by jonathanchrisp** [auth0/lock#890] opened 2017-03-02 03:52 UTC
## Overview
Lock `authenticated` event emitted when the user closes the authorization dialog by clicking cancel. I would expect this to raise the `authorization_error` event, however, it believes authorization was successful.

I haven't trawled through the code as of yet but wanted to raise an initial issue to see if this problem is known. If so is there a recommended workaround? 

- [x] Code snippet - see below 
- [x] Screenshots - see below
- [x] Lock version - `v10.11.0`
- [x] Browser & OS - `Chrome / Mac OS Sierra`

![iftdvdwu7v](https://cloud.githubusercontent.com/assets/406799/23492193/11f62d40-ff57-11e6-9df6-98e7f8fcee57.gif)

Original recording here http://recordit.co/IftdvdWU7V.

```js
export function authenticate() {
  const AUTH0_CLIENT_ID = 'xxxxxxxxxxx'
  const AUTH0_DOMAIN = 'xxxxxxxxxxx'

  const lock = new Auth0Lock(AUTH0_CLIENT_ID, AUTH0_DOMAIN, {
    auth: { redirect: false },
    allowedConnections: ['spotify'],
    languageDictionary: { title: 'Testing!!' },
  })

  return dispatch => {
    lock.on('authenticated', (authResult) => {
      console.log(authResult) // error here!!

      if (authResult.errorDescription) return dispatch(authError(authResult.errorDescription))

      lock.getUserInfo(authResult, (error, profile) => {
        if (error) return dispatch(authError(error.errorDescription))

        localStorage.setItem('accessToken', authResult.accessToken)

        return dispatch(authSuccess(profile))
      })
    })

    lock.on('authorization_error', (error) => {
      return dispatch(authError(error.errorDescription))
    })

    lock.on('unrecoverable_error', (error) => lock.hide())

    lock.show()
  }
}
```
Code above returns a function for redux thunk.

**Comment by jonathanchrisp** [comment] 2017-03-20 10:28
@luisrudge did you have a chance to look into this? Happy to look into this if needed.

**Comment by luisrudge** [comment] 2017-03-20 14:23
Hi @jonathanchrisp. I'm still trying to find a reasonable fix for this, but it might take a while. For now, you can use `auth: { redirect: false, responseType: 'code' },` instead, it will work just fine. The issue is when you use `responseType: token` (the default). Does that work for you right now?

**Comment by luisrudge** [comment] 2017-03-21 14:03
@jonathanchrisp sorry! nevermind what I said before. I found the root cause of the issue and I'll fix it for the next release. Also, responseType code wouldn't work any way 😭

**Comment by luisrudge** [comment] 2017-03-21 18:37
This was fixed in https://github.com/auth0/auth0.js/pull/395 and will be in the next release! Thanks for your patience and all the help!

**Closed by luisrudge** 2017-03-21 18:37 UTC
