### ISSUE TITLE
Username field on the lock allows spaces.

### ISSUE THREAD

**Issue by thduttonuk** [auth0/lock#1855] opened 2020-04-30 08:48 UTC
![image](https://user-images.githubusercontent.com/5237694/80690950-725c5480-8ac7-11ea-84f3-340678364d4f.png)

### Description

We are using the latest version of the lock 11.23.1 and it allows spaces in the username. 

### Reproduction

Enter a space in the username on the signup screen.

### Environment

We are using Angular with the auth0-lock package.
Also we are adding addition fields.

**Comment by thduttonuk** [comment] 2020-04-30 08:59
Also the documentation does not say it allows spaces
https://auth0.com/docs/connections/database/require-username

**Comment by stevehobbsdev** [comment] 2020-05-01 13:09
Thanks for raising @thduttonuk - let us look into it.

**Comment by thduttonuk** [comment] 2020-05-01 13:54
@stevehobbsdev I have looked into this more. Its when you have "Use my own database" turned on.

**Comment by stevehobbsdev** [comment] 2022-09-09 12:19
Thanks for your patience here! I appreciate there's been a long time since we looked into this issue.

I can reproduce this with a custom database. I've noticed from the client setting file that is downloaded when Lock initialized, that the validation rules around username are only transmitted to us if the "Username length" settings are enabled in the dashboard. And to enable those, you have to turn on "Import Users to Auth0":

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/766403/189347939-9295a418-7c4b-4966-b32b-533b16e64d2c.png">

I am currently querying internally as to whether this is intended behaviour or not.

**Comment by stevehobbsdev** [comment] 2022-09-09 15:26
I heard back from the team internally; this is in fact expected behaviour, but is something they plan on improving. Once they implement that on the server, those validation rules should be picked up by Lock.

I'll close this for now and thanks again for your patience.

**Closed by stevehobbsdev** 2022-09-09 15:26 UTC
Labels: needs investigation
