### ISSUE TITLE
Lock + Meteor breaks when trying to require & use blueimp-md5

### ISSUE THREAD

**Issue by musshush** [auth0/lock#466] opened 2016-07-01 09:39 UTC
After submitting email address on forgot password view, it goes back to the login screen with the form appended underneath of login form.
Shouldn't it show a message instead, saying something like... an email has been sent to reset your password?

<img width="315" alt="screen shot 2016-07-01 at 10 38 59" src="https://cloud.githubusercontent.com/assets/864185/16517935/1221a604-3f78-11e6-8ab2-4598bbdb92e0.png">

**Comment by gnandretta** [comment] 2016-07-01 14:56
@musshush Hi! are you using webpack to bundle you app?

**Comment by leilafi** [comment] 2016-07-01 15:54
@germanmatosas yes we are.

**Comment by gnandretta** [comment] 2016-07-05 13:19
Should be fixed on 10.0.0-rc.2. Please reopen if the problem persist.

**Comment by wallslide** [comment] 2016-08-09 08:33
I'm still seeing this same behavior on `10.0.2`. We are using meteor `1.4` w/ import statements.

**Comment by gnandretta** [comment] 2016-08-09 13:27
@wallslide do you see any errors in the console?

**Comment by wallslide** [comment] 2016-08-10 01:06
I do get an error in the console. It doesn't seem related but...
![image](https://cloud.githubusercontent.com/assets/917069/17538582/bb7e2f6e-5ee1-11e6-80b3-4cf82483fa96.png)


Here I enter in the email address:
![image](https://cloud.githubusercontent.com/assets/917069/17538613/fe66d5b0-5ee1-11e6-8b23-023999314140.png)

And the following state of the UI:
![image](https://cloud.githubusercontent.com/assets/917069/17538625/109cc140-5ee2-11e6-95d6-e52528f994ea.png)

**Comment by gnandretta** [comment] 2016-08-10 13:22
Yes, that error is the cause for the issue. Can you provide a sample so I can debug it?

**Comment by wallslide** [comment] 2016-08-11 04:39
@gnandretta I've created a repository to highlight the problem https://github.com/wallslide/auth0-reset-password-problem

**Comment by Maxhodges** [comment] 2016-08-29 16:14
bump. 20 days and counting. How are we supposed to deploy this to production? Shouldn't you guys be making bugs a priority?

**Comment by hzalaz** [comment] 2016-08-29 21:01
@wallslide thanks for the sample, there is an issue with the lib used to calculate the md5 of the email that is sent to gravatar. (Not sure why it breaks the flow).

A quick fix, until we sort that out, is to disable the avatar feature by initialising Lock like this

```js
  Lock = new Auth0Lock(
    AUTH0_CLIENT_ID,
    AUTH0_DOMAIN, {avatar: null});
```

**Comment by wallslide** [comment] 2016-08-30 07:04
Thanks. Setting avatar to `null` let us get past that problem for now.

**Closed** 2016-09-19 17:10 UTC
Labels: bug, P3: Important, S3: Broken, v10
