### ISSUE TITLE
Unable to access signup panel

### ISSUE THREAD

**Issue by nathanBrenner** [auth0/lock#1134] opened 2017-10-06 19:03 UTC
snippet from the typescript class for the Angular service:
```
export class Auth {
	lock: Auth0LockStatic = new Auth0Lock(myConfig.clientID, myConfig.domain, {});

	constructor() {
		this.lock.on('authenticated', (authResult) => this.handleAuthResult(authResult))
	}
	showLogin(): void {
		this.lock.show();
	}
}
```

As you can imagine, I've got routed component that calls the lock to show in the ngOnInit lifecycle hook. 

Lock version: `auth0-lock@10.21.1`

![screen shot 2017-10-06 at 12 00 25 pm](https://user-images.githubusercontent.com/9688337/31293960-038cc45c-aa8e-11e7-9b8d-bb53d8a38302.png)

When I click on the sign up text, the lock should show the sign up fields. This is the behavior I get on Firefox@55.0.3 (64-bit), Safari@11.0. But on Chrome@61.0.3163.100, the lock closes, and I get these errors printed in the chrome devtools console:

![screen shot 2017-10-06 at 11 59 36 am](https://user-images.githubusercontent.com/9688337/31293974-128eb262-aa8e-11e7-93ff-f57d53017ca3.png)

OS is MacOS 10.16.6

**Comment by luisrudge** [comment] 2017-10-06 19:05
This is because you're using react@16. Dupe of https://github.com/auth0/lock/issues/1096

**Closed by luisrudge** 2017-10-06 19:05 UTC
