### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by nelix** [auth0/lock#54] opened 2014-10-03 09:30 UTC
I tried to load this using webpack but I did not very very far due to not knowing what loaders it would require...
Any advice?

**Comment by carnevalle** [comment] 2015-04-27 21:12
I can't get above example to work with webpack. Anyone have a complete working example?

**Comment by cancan101** [comment] 2015-04-29 17:48
I also cannot get the above to work.
Also what `devDependencies` are needed?

**Comment by kpgarrod** [comment] 2015-05-07 10:13
I'm also having problems with this. Did anybody get it right? I'm getting json errors.

**Comment by jfromaniello** [comment] 2015-05-19 18:00
Can you guys try with `v7.5.4` just released?

Thanks a bunch

**Comment by cancan101** [comment] 2015-05-19 20:35
@jfromaniello Do you have an example how the webpack file should look?

**Comment by kpgarrod** [comment] 2015-05-20 07:06
@jfromaniello I would also like an example please. I tried again today with v7.5.4 but did not succeed. 
I did get the app to build using @nelix's loader definitions, however it doesn't run.

I'm not sure if this is still the same issue - I am trying to use Lock with angular and am now getting an error from auth0-angular:

````
ReferenceError: Auth0Widget is not defined
    at constructorName (webpack:///./~/auth0-angular/build/auth0-angular.js?:185:21)
    at angular.module.provider.init (webpack:///./~/auth0-angular/build/auth0-angular.js?:203:31)
    at eval (webpack:///./coachesNetwork/index.js?:21:18)
    at Object.invoke (webpack:///./~/angular/angular.js?:4426:17)
    at runInvokeQueue (webpack:///./~/angular/angular.js?:4332:35)
    at eval (webpack:///./~/angular/angular.js?:4341:11)
    at forEach (webpack:///./~/angular/angular.js?:336:20)
    at loadModules (webpack:///./~/angular/angular.js?:4322:5)
    at createInjector (webpack:///./~/angular/angular.js?:4248:11)
    at doBootstrap (webpack:///./~/angular/angular.js?:1625:20)
````
I see that auth0-angular throws that error if window.Auth0Lock is not defined.

I have tried including the library in a couple of ways: 
- `var Auth0Lock = require('auth0-lock')`
- `new webpack.ProvidePlugin({
    Auth0Lock: 'auth0-lock/index'
  })`

**Comment by cristiandouce** [comment] 2015-05-20 14:18
@kpgarrod 
1. If you use the `index.js` to load the Auth0Lock, you must build it with all it's browserify transformations. I'd recommend you to just load the build from `auth0-lock/build/auth0-lock.js`
2. What version of `auth0-angular` are you using?

**Comment by kpgarrod** [comment] 2015-05-22 05:39
@cristiandouce I don't see a build directory in this repository. I am using auth0-angular 4.0.4.

**Comment by cristiandouce** [comment] 2015-05-22 13:17
https://github.com/auth0/lock/tree/v7.5.4/build

The build directory is never pushed to master branch or any development branch, just the releases branches.

What is important is that if you installed lock with bower you should find that build inside your code.

**Comment by kpgarrod** [comment] 2015-05-22 13:25
@cristiandouce: ah, that explains it. I'm not using bower anymore. I am installing with npm, but I still want to get the build code.

**Comment by cristiandouce** [comment] 2015-05-22 13:26
You should still have that build directory from npm install. Is that not the case?

**Comment by kpgarrod** [comment] 2015-05-22 13:30
no

**Comment by jfromaniello** [comment] 2015-05-22 13:46
@kpgarrod @cristiandouce the `build` directory is not pushed to npm on purpose, if you install with npm you build with browserify.

If you want to install with npm and at the same time have the build folder in the release tag you can use this and install from github:

```
npm install auth0/lock\#v7.5.4
```

**Comment by jfromaniello** [comment] 2015-05-22 13:48
no that doesn't work either because is npm ignored :(

**Comment by kpgarrod** [comment] 2015-06-01 10:16
@jfromaniello: so any solution for this issue? I have been loading from cdn but the performance is sometimes very slow from where I am. That is making it difficult for me to work.

**Comment by jfromaniello** [comment] 2015-06-01 11:44
@kpgarrod can you try like this:

```
npm i --save https://github.com/auth0/lock/archive/v7.5.4.tar.gz
```

**Comment by jfromaniello** [comment] 2015-06-01 12:02
@kpgarrod btw, regarding this:

> I have been loading from cdn but the performance is sometimes very slow from where I am

where are you from? (country)

**Comment by kpgarrod** [comment] 2015-06-01 12:02
South Africa

**Comment by kpgarrod** [comment] 2015-06-01 12:43
I tried installing from that url. I certainly do get the build directory that way, however it still doesn't work for me.

Webpack gives me this warning:

WARNING in ./~/auth0-lock/build/auth0-lock.js
```Critical dependencies:
1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/auth0-lock/build/auth0-lock.js 1:113-120```

and when I run the app I get this angular error: 
```Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module {} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object```

In my limited experience, that usually means there is no `export` for a module that is being required.

**Comment by kpgarrod** [comment] 2015-06-02 06:43
@jfromaniello I made pull requests for auth0-jwt, auth0-storage and auth0-angular to include an export statement like this:

>if (typeof module !== "undefined" && typeof exports !== "undefined" && module.exports ===
  exports) {
  module.exports = 'auth0-lock';
}

That seems to be how other libraries deal with this issue.

My pull requests haven't been accepted, but I am successfully using my branch in my app. I think the same thing is needed here.

I wasn't sure where to add the statement in this library, so haven't made a pull request here, but it would be great if you could add the export to this and your other libraries.

**Comment by jfromaniello** [comment] 2015-06-02 12:51
@kpgarrod I'll look into that.

In addition to that, I want to point out that we made a successful change to our cdn and we added a node to South Africa.

We will love to know the response time now from your place to cdn.auth0.com now.

If you dig/nslookup cdn.auth0.com this is the ip it should be resolving: 41.185.31.164.

Thanks a lot for your troubleshooting

**Comment by kpgarrod** [comment] 2015-06-03 08:24
@jfromaniello the cdn does resolve correctly and ping time is about 12ms, thanks!

**Comment by cristiandouce** [comment] 2015-06-03 15:13
@kpgarrod @cancan101 @nelix @rayvace @carnevalle we have now an example using webpack in this repository.

Unless it doesn't work for you, I'm closing this issue for now.

You can follow the instructions here: https://github.com/auth0/lock/tree/master/examples/webpack#running-the-example

**Closed by cristiandouce** 2015-06-03 15:13 UTC
Labels: enhancement

**Comment by kpgarrod** [comment] 2015-06-05 12:03
@cristiandouce Unfortunately this is still not working for me. 
If I require Lock as in your example, I get `Auth0Widget is not defined` from auth0-angular.

I can get my app to build and basically run by requiring lock like this: `var Auth0Lock = require('auth0-lock/build/auth0-lock');`, but I get warnings from webpack:

>WARNING in ./~/auth0-lock/build/auth0-lock.js
>Critical dependencies:
>1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try >to require the original source to get better results.
> @ ./~/auth0-lock/build/auth0-lock.js 1:113-120

when I try to signin with Lock, I get an error message about `md5` being unavailable.

I had a message from Gonto to say that the other libraries have already been updated, but I don't see that and am still having issues with them(auth0-angular, auth0-storage and auth0-jwt) - maybe not all of them, I haven't had time to debug properly.

**Comment by cristiandouce** [comment] 2015-06-05 12:24
We dont have auth0-angular in the example...

Doesthe example with webpack under thr rxamples folder work for you?

If it does then we can scale the issue to debug auth0-angluar instead of lock.

**Comment by kpgarrod** [comment] 2015-06-05 12:39
@cristiandouce yes, the example works correctly for me.

**Comment by cristiandouce** [comment] 2015-06-05 14:10
@kpgarrod cool then. Would you mind open an issue there then, with more detail on your configuration for using webpack with auth0-angular?

Also, if you have a seed project that reproduces the bug it would help to debug.

**Comment by Jbarget** [comment] 2016-06-29 10:05
Hi all,

having trouble getting oAuth to run on my production build on aws.

![screen shot 2016-06-28 at 18 14 41](https://cloud.githubusercontent.com/assets/11725595/16448350/e60f88f0-3de8-11e6-8e8b-2c580ad2262f.png)

Locally my dev build works all fine so I tried to add in the necessary loaders as in the [example](https://github.com/auth0/lock/tree/master/examples/webpack#running-the-example) but no luck.

Any help would be much appreciated!

**Dev webpack config:**

```
const webpack = require('webpack');

module.exports = {
  entry: [
    'webpack-dev-server/client?http://localhost:8080/',
    'webpack/hot/dev-server',
    './src/index.js'
  ],
  output: {
    filename: 'bundle.js',
    path: '/'
  },
  resolve: {
    extensions: ['', '.jsx', '.scss', '.js', '.json']
  },
  module: {
    preLoaders: [
      {test: /\.(js|jsx)$/, loader: 'eslint-loader', exclude: /node_modules/}
    ],
    loaders: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loaders: ['react-hot','babel']
      },
      {
        test: /\.scss$/,
        loaders: ['style', 'css?sourceMap', 'sass?sourceMap']
      }
    ]
  },
  eslint: {
    configFile: './.eslintrc'
  },
  externals: {
    'cheerio': 'window',
    'react/lib/ExecutionEnvironment': true,
    'react/lib/ReactContext': true,
  },
  debug: true,
  devtool: 'source-map',
  devServer: { hot: true, historyApiFallback: true },
  plugins: [ new webpack.HotModuleReplacementPlugin() ],
  inline: true,
  progress: true,
  colors: true
};

```

**Production config**:
```
const config = require('./webpack.development.config.js');
const webpack = require('webpack');
const path = require('path');

config.plugins.push(
  new webpack.DefinePlugin({
    'process.env': {
      'NODE_ENV': JSON.stringify('production')
    }
  })
 );

config.module.loaders.push(
  {
    test: /node_modules\/auth0-lock\/.*\.js$/,
    loaders: [
      'transform-loader/cacheable?brfs',
      'transform-loader/cacheable?packageify'
    ]
  }, {
    test: /node_modules\/auth0-lock\/.*\.ejs$/,
    loader: 'transform-loader/cacheable?ejsify'
  }, {
    test: /\.json$/,
    loader: 'json-loader'
  }
);

config.plugins.push(new webpack.optimize.CommonsChunkPlugin('common.js'));
config.plugins.push(new webpack.optimize.UglifyJsPlugin({compress: {warnings: false}}));
config.plugins.push(new webpack.optimize.DedupePlugin());
config.plugins.push(new webpack.optimize.AggressiveMergingPlugin());

config.entry = ['./src/index.js'];

config.output = {
  path: path.join(__dirname, '/dist/'),
  filename: '[name].js',
  publicPath: '/'
};

module.exports = config;

```
