### ISSUE TITLE
[v10] Lock SVGs are not getting displayed

### ISSUE THREAD

**Issue by shuaibiyy** [auth0/lock#502] opened 2016-07-24 05:43 UTC
I'm using lock v10.0.0, and I have a Webpack setup based on the example in `examples/bundling/webpack`.

The lock SVGs don't display in Chrome, Firefox and Safari. I use a Macbook. See screenshots below:

<img width="354" alt="screen shot 2016-07-24 at 13 38 56" src="https://cloud.githubusercontent.com/assets/1766965/17082098/3c55ffa4-51a4-11e6-87e6-aaf4c0e280f2.png">
<img width="338" alt="screen shot 2016-07-24 at 13 39 22" src="https://cloud.githubusercontent.com/assets/1766965/17082099/3c56b4ee-51a4-11e6-8168-aa86e448b122.png">

**Comment by gnandretta** [comment] 2016-07-25 13:11
Hi, it looks like a stylesheet is setting the background of all svgs to white. Can you provide a sample reproducing the issue?

**Comment by shuaibiyy** [comment] 2016-07-26 14:56
Hi @gnandretta ! You are right! A very rookie mistake on my path. Thank you!

**Comment by gnandretta** [comment] 2016-07-26 18:31
I'll reopen this, so we can add defaults for common properties.

**Comment by gnandretta** [comment] 2016-07-28 19:23
Fixed on #506 .

**Closed by gnandretta** 2016-07-28 19:23 UTC
Labels: v10
