### ISSUE TITLE
Footprint of lock is RIDICULOUSLY huge (almost 2MB)

### ISSUE THREAD

**Issue by AndreasGalster** [auth0/lock#1007] opened 2017-05-19 10:13 UTC
I usually don't act a bit rude but .... guys, I was trying to figure out why our app has such a huge footprint, so eventually I found the culprit. Here are two screenshots with and without auth0 lock imported on Webpack. 

![2017-05-19 4](https://cloud.githubusercontent.com/assets/3836411/26243410/5f3b1b0c-3cbe-11e7-9fcc-ec8061ab7d49.png)
![2017-05-19 3](https://cloud.githubusercontent.com/assets/3836411/26243411/5f87b44e-3cbe-11e7-9e31-09eaa6e735fe.png)

Are there any ways to reduce the size of this? It's ... it's just ridiculous, can't find any other word for it... Can we only import what's needed? This is just way too huge

**Comment by amertum** [comment] 2017-05-19 11:14
Related to #964 and #113

**Comment by luisrudge** [comment] 2017-05-19 13:17
Dupe of https://github.com/auth0/lock/issues/113#issuecomment-292255745

**Closed by luisrudge** 2017-05-19 13:17 UTC
