### ISSUE TITLE
Critical bug trying to sign up using pop-up mode in Chrome Browser in iOS 8 

### ISSUE THREAD

**Issue by carnevalle** [auth0/lock#214] opened 2015-09-04 19:23 UTC
I am experiencing a critical bug on iOS (8) using the newest Chrome Browser. 

When trying to sign up it opens a new window, but nothing happens after this. If I close the window the Lock Dialog just stays in busy mode - no errors or anything. So users can't sign up using Lock.

I am also experiencing a problem with login, as mentioned here #71, where the popup windows doesn't close automatically, but login is completed when manually closing the window. 

I am using Lock 7.8.1.

**Comment by will-hancock** [comment] 2015-12-08 12:05
Is this bug still open? We are experiencing it on a high traffic site and is generating a large quality of Customer Support tickets.

Any info would be greatly appreciated.

**Comment by michaek** [comment] 2016-05-18 15:38
I was not able to reproduce this issue after upgrading to Chrome 50 (current version as of this comment). Are you still seeing the issue?

**Comment by prabhatsharma** [comment] 2016-06-01 00:15
I am still facing this problem on android (5.1.1) , one plus 2 on chrome 50.0.2661.89 . However, people in field can have different versions. How do we handle this. It works perfectly well when I run it in ionic view on same phone.

**Comment by prabhatsharma** [comment] 2016-06-01 00:23
Lock version 9.2.1

**Comment by prabhatsharma** [comment] 2016-06-01 00:36
Video of the issue https://youtu.be/6TMpiyzjcDY

**Comment by prabhatsharma** [comment] 2016-06-01 00:41
The video does not ask for facebook authentication again since I am already authenticated in browser once.

**Comment by prabhatsharma** [comment] 2016-06-01 10:56
ok guys. The simple solution is to avoid chrome altogether and use inbrowser app. Install it using following command:

`cordova plugin add cordova-plugin-inappbrowser`

and then your cordova app will not have any trouble closing the external chrome tab/window.

Hope this helps...

**Comment by krismp** [comment] 2017-01-23 07:11
Hi guys, Im still facing this issue, but it only on iOS, Im using cordova, Already installed `cordova-plugin-inappbrowser` too.

Im using the latest version of auth0-lock (currently: 10.0.1). Any suggestions?

https://github.com/auth0/lock/issues/214#issuecomment-222959398

**Comment by hzalaz** [comment] 2017-01-31 18:19
Will close this one since iOS 8 is already an old OS. We recommend using plain old redirect in mobile web since it's easier to debug and you don't depend on the mobile browser implementing the window.open correctly. 

Chrome iOS had a history of fixing and breaking it on every update and it's almost impossible to debug what's going on.

**Closed by hzalaz** 2017-01-31 18:19 UTC
Labels: bug
