### ISSUE TITLE
Upgrading from 6.12.1 to 7.0.0 breaks apps loaded off file://

### ISSUE THREAD

**Issue by chrisronline** [auth0/lock#112] opened 2015-01-29 16:52 UTC
https://ask.auth0.com/t/auth0-and-chromium-apps-node-webkit/471/8

That happens when we upgrade (and happened on a previous version of auth0-lock too).

Any thoughts?

**Comment by pose** [comment] 2015-02-05 22:55
Hi @NetEvolutions,

Can you send us an example project to support@auth0.com so we can reproduce the bug? 

Thanks,

**Comment by pose** [comment] 2015-02-05 22:56
@chrisronline Need to get back to you on that using the node-webkit to reproduce the error, I think these are two different issues but I'll research both first. Thanks.

**Comment by gdjennings** [comment] 2015-02-15 03:04
I am also seeing white screen of death on android + cordova + DB connection login + lock-7.1.1

**Comment by pose** [comment] 2015-02-19 13:57
Hi,

@gdjennings @NetEvolutions We were able to reproduce the issue and should be fixed in Auth0 7.1.3. If that's not the case, let me know and I'll create a new issue.

@chrisronline Still working on the issue, I think you should be able to make it work with 7.1.3 by disabling by setting  `sso: false` but I need to get back to you on that.

Thanks again,

**Comment by gdjennings** [comment] 2015-02-21 02:50
@pose I can verify that android is working again in 7.1.3

**Comment by pose** [comment] 2015-02-22 13:26
@gdjennings Awesome, thanks! Now we only need to wait for the node-webkit part to close the issue.

**Comment by pose** [comment] 2015-02-25 16:59
Hi @chrisronline,

Can you try now with `7.1.4` and setting `sso: false` flag on `signin` / `signup`? The problem is that in `7.x` is no longer using by default the `/ro` endpoint and that should be explicitely enabled by setting `sso: false`. Feel free to re open the issue if that does not solve your problem.

Thanks again,

**Closed by pose** 2015-02-25 16:59 UTC
Labels: bug

**Comment by chrisronline** [comment] 2015-02-27 02:21
Works. Thanks much!

**Comment by pose** [comment] 2015-02-27 03:47
@chrisronline :+1:
