### ISSUE TITLE
v11 embedded height too large (100vh) on mobile

### ISSUE THREAD

**Issue by camhart** [auth0/lock#1709] opened 2019-07-24 05:25 UTC
### Description

I'm embedding lock using the `container` option.  When embedded and viewed on a mobile device in portrait mode, the `div` with `class` `auth0-lock-cred-pane-internal-wrapper` has a height of 100vh, which isn't correct.  I believe it should be `auto`.

When `100vh` is used, the lock "widget" is 100vh forcing the sign in button and other details to be cut off the screen if the lock "widget" doesn't start at height 0.  For example, if you have a menu bar at the top.

### Prerequisites

* [ x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [ x] Did you check the documentation in the [README](https://github.com/auth0/lock) or on [our docs site](https://auth0.com/docs/libraries/lock/v11)?
* [x ] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [ x] Are you reporting this to the correct repository?
* [x ] Are there any related or duplicate [Issues](https://github.com/auth0/lock/issues) or [PRs](https://github.com/auth0/lock/pulls) for this issue?

### Environment

Please provide the following:

* Lock version: 11.17.0
* Browser version: chrome 75.0.3770.142
* OS: windows 10
* running in vue.js app using vuetify.

### Reproduction

Embed the lock using the container option.  Put anything above the container with a height > 0.   View on mobile device or using chrome dev tools in portrait mode.  The lock will force a scroll with a bunch of unnecessary whitespace.

Please include:

![image](https://user-images.githubusercontent.com/3038809/61767311-be3fd780-ad98-11e9-94dc-5514f19ee0ba.png)

**Comment by camhart** [comment] 2019-07-24 21:07
For anyone else facing this, add this css and it should do the trick.  Make sure it's not "scope" limited in anyway (like using scope keyword in Vuejs application).

  ```
.auth0-lock-cred-pane-internal-wrapper {
    height: auto !important;
  }
```

**Comment by camhart** [comment] 2019-10-26 10:14
This is still an issue @stalebot.

**Comment by stevehobbsdev** [comment] 2020-01-22 13:20
@camhart apologies that this has taken so long to come around. We now have a PR that should hopefully fix this. Once it has been merged and released, I'll circle back around to verify that it has indeed fixed your issue.

#1785

**Comment by stevehobbsdev** [comment] 2020-01-29 15:21
This is now released in v11.20.4. Closing this for now, if you feel it hasn't solved your issue, please feel free to continue the discussion.

**Closed by stevehobbsdev** 2020-01-29 15:21 UTC

**Comment by Niclas1976** [comment] 2020-12-09 14:48
Issue still remains, I think version is 11.26.

Solved it quick and dirty by adding this to the head of the Universal login HTML:

```
<head>
<style>
.auth0-lock-cred-pane-internal-wrapper {
  height: auto !important;
}
</style>
</head>
```

**Comment by brendanlong** [comment] 2021-01-27 00:07
We're seeing this as well on v11.27 and v11.28. You can see our login page here: https://luminate.arena.io

Which looks like this if you make the window phone-sized:

![Screen Shot 2021-01-26 at 17 05 38](https://user-images.githubusercontent.com/1447206/105922978-ed23b300-5ff8-11eb-98b0-f05695f37ec5.png)

**Comment by brendanlong** [comment] 2021-01-27 00:10
Looking at #1785, I think the problem is that in our case we have HTML outside of the lock, so the logic correctly makes the lock the size of the entire screen, but that sizing isn't desirable unless the lock is the only thing on the screen. Is there a way to tell the lock that it doesn't own the screen? Auth0's universal login customization isn't very useful if we're not allowed to display anything except the lock.
