### ISSUE TITLE
Submit button is lost on safari mobile when keyboard is up

### ISSUE THREAD

**Issue by alexiaharal** [auth0/lock#1991] opened 2021-05-05 11:43 UTC
### Describe the problem
On safari mobile, using the passwordless method, when a user clicks the text field to enter their email, the keyboard appears and the submit button disappears. When you close the keyboard, the terms checkbox disappears and you still have to scroll all the way down to find the submit button which is part of a black screen.  

### What was the expected behavior?
When a user clicks the text field to enter their email, the submit button should be visible with or without the keyboard visible, without the need to scroll down. Terms checkbox shouldn't disappear. 

### Reproduction
Step 1
Create a simple passwordless app
Step 2 
Click the email field to enter email
(Submit button disappears)
Step 3
Click `done` on the keyboard, or close the keyboard
(Submit button still not visible)
Step 4 
Scroll down and you will find the submit button as part of a black screen

### Environment
Tested on version: "11.28.1"

**Comment by stevehobbsdev** [comment] 2021-05-12 11:20
Hi @alexiaharal,

I'm not able to reproduce this given the steps above. It might help to provide the version of iOS you're testing on and perhaps which device for the screen size.

This is from v11.30.0 using an iPhone 6s simulator:

https://user-images.githubusercontent.com/766403/117966851-4ac7db00-b31c-11eb-9b7e-48266ddc3297.mov

**Comment by alexiaharal** [comment] 2021-05-12 15:43
Hi @stevehobbsdev 

We tested on Iphone XS Max with the latest version of iOS installed.

**Comment by stevehobbsdev** [comment] 2021-05-24 13:42
@alexiaharal We see the request that has been raised internally about this issue and I can now see the problem you're facing, and that my steps above actually show the problem in action. I have responded internally to the account handler but I will also relay my response here.

After having dived into this deeper, what you're seeing is the expected behaviour on iOS. We already have provisions in place to respond to changes in window size/viewport, etc which are changed on Android when the soft keyboard is shown. Unfortunately in iOS/Safari, no resize event s raised nor the viewport changed when the soft keyboard is shown and so we have no way to detect when this situation occurs.

We could potentially do something where we react to focus/blur events on all the input boxes and put a fixed-height margin on below the button, but this is error prone and not something I can recommend we put into the core library. However, if you are using (or able to use) a custom template for Lock you may be able to handle this yourself by adding these event handlers and adding the necessary style rules. [This third-party article](https://medium.com/@im_rahul/safari-and-position-fixed-978122be5f29) explains the problem and potential workarounds.

Closing for now but happy to continue the conversation.

**Closed by stevehobbsdev** 2021-05-24 13:42 UTC
Labels: bug report, cannot repro, needs more info
