### ISSUE TITLE
Different format in error messages.

### ISSUE THREAD

**Issue by paulioceano** [auth0/lock#1328] opened 2018-04-02 18:58 UTC
This probably has more to do with the library than the sample, but when trying to Signup or Login with a blank password, it shows an error saying that that field can't be blank, but the format of the messages are different:

For Signup is black background with red letters and for Login is white background with black letters,

![capture-for-jira-screenshot-20171206-142058-574](https://user-images.githubusercontent.com/15818783/33724207-2d7454be-db45-11e7-909d-ffe1f7a9750e.png)
![capture-for-jira-screenshot-20171206-142115-746](https://user-images.githubusercontent.com/15818783/33724209-2dd6b26c-db45-11e7-9714-0c5437674c3f.png)

**Comment by luisrudge** [comment] 2018-04-29 15:10
duplicate of https://github.com/auth0/lock/issues/1328

**Closed by luisrudge** 2018-04-29 15:10 UTC
