### ISSUE TITLE
Objects are not valid as react child in SocialButtonPane on Internet Explorer

### ISSUE THREAD

**Issue by Filipvdb321** [auth0/lock#1018] opened 2017-05-30 06:33 UTC
When showing the login window with lock we get the following exception in Internet Explorer (11 and 10):
` Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.`

On other browsers (chrome, firefox, safari) this works fine.

**Code causing the problem:**
`this.lock.show()`

**Lock version:** `10.16.0`

**Full stack:**
```

   JavaScript Console is attached and accepting commands.
   
      %c prev state color: #9E9E9E; font-weight: bold [object Object]
      %c action     color: #03A9F4; font-weight: bold [object Object]
      %c next state color: #4CAF50; font-weight: bold [object Object]

   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
Invariant Violation: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   at invariant (http://localhost:3000/_next/-/commons.js:56:5)
   at traverseAllChildrenImpl (http://localhost:3000/_next/-/commons.js:13879:23)
   at traverseAllChildren (http://localhost:3000/_next/-/commons.js:13907:3)
   at instantiateChildren (http://localhost:3000/_next/-/commons.js:26511:7)
   at _reconcilerInstantiateChildren (http://localhost:3000/_next/-/commons.js:31317:13)
   at mountChildren (http://localhost:3000/_next/-/commons.js:31356:7)
   at _createInitialChildren (http://localhost:3000/_next/-/commons.js:28356:9)
   at mountComponent (http://localhost:3000/_next/-/commons.js:28175:7)
   at mountComponent (http://localhost:3000/_next/-/commons.js:2219:5)
   at mountComponent (http://localhost:3000/_next/-/commons.js:14369:5)
   SCRIPT5022: Objects are not valid as a React child (found: List [ [object Object], [object Object] ]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SocialButtonsPane`.
   File: lier_be, Line: 14373, Column: 5
```

**Comment by luisrudge** [comment] 2017-05-30 13:55
Hi, this is a dupe of https://github.com/auth0/lock/issues/920 - no one could build a sample repo at the time. Can you build one now? This is probably related to some dependency you're using, not with lock itself.

**Comment by luisrudge** [comment] 2017-05-31 15:46
Sorry but you have a huge list of dependencies and one of them is messing up Lock. I can help you debug the issue once you pinpoint which package is causing this conflict.

I built an example in #920 with create-react-app and it works just fine:
![cra-lock](https://cloud.githubusercontent.com/assets/941075/23864824/7c93a1de-07f2-11e7-8b91-05d2e6a366ac.gif)

**Comment by Filipvdb321** [comment] 2017-05-31 16:27
Yes, when I try a basic app with only lock it works for me as well on IE11.
I will try to find the cause.
Do you have any idea why for IE11 SocialButtonPane could receive a List instead of an Array? It would give me a clue where to look. How is this list created/received?

**Comment by luisrudge** [comment] 2017-05-31 16:41
I don't know.. Not sure why this would happen. the render is pretty straightforward: https://github.com/auth0/lock/blob/bb92858006eb1b39e38a9fb9000704554dc69997/src/field/social/social_buttons_pane.jsx#L19

**Comment by Filipvdb321** [comment] 2017-06-01 05:23
Hi , I found the issue.
For IE I needed to import `babel-polyfill`but this was causing the problem with lock.
If I do the import after the lock import, it works:

```
import Auth0Lock from 'auth0-lock';
import 'babel-polyfill';
```

**Comment by luisrudge** [comment] 2017-06-01 06:18
Hi, thanks for getting in touch. This is even weirder than before, since vanilla react+lock works without the polyfill, but I'm glad you figured it out! cc @glortho @Serfenia

**Closed by luisrudge** 2017-06-01 06:18 UTC
