### ISSUE TITLE
Problem opening the keyboard to enter password on iOS 13 and iOS 14 running on BrowserStack

### ISSUE THREAD

**Issue by fernandomunizz89** [auth0/lock#1936] opened 2020-10-15 15:11 UTC
When trying to enter the password, the device keyboard opens in error.
Problem opening the keyboard to enter password on iOS 13 and 14

### What was the expected behavior?
The keyboard was expected to open normally to enter the password.

### Reproduction
Running on BrowserStack
Call /authorize endpoint, will redirect to hosted login page.
Touch the password entry, the on-screen keyboard will appear in error.

### Environment
- **Version of Lock used:** 11.27
- **Which browsers have you tested in?** Safari

iPhone XS on iOS 13 also on iOS 14
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/42263615/96149789-a1de0c80-0f01-11eb-8301-e119485e878d.gif)

**Comment by stevehobbsdev** [comment] 2020-11-09 15:54
Thanks for the report @fernandomunizz89 - I am able to reproduce this on BrowserStack but I'm not sure why it's happening. Are you able to reproduce this with any other apps or on a physical device? Have you contacted BrowserStack about the issue?

**Comment by stevehobbsdev** [comment] 2020-12-02 11:51
Closing for now as I'm unable to reproduce this on a real physical device. Could be an anomaly with how BrowserStack is working in this case, but I'm not confident it's an SDK issue.

**Closed by stevehobbsdev** 2020-12-02 11:51 UTC
Labels: bug report

**Comment by tjrobinson** [comment] 2021-11-12 16:59
> From what I can gather, BrowserStack uses Screen Mirroring to display the device. Apple introduced a security update as of iOS 13 where passwords type inputs hide the keyboard on the screen you're casting/mirroring to. You can replicate this by testing it on an Apple TV, or by sharing your screen during a call. Therefore, it's not really a bug, but a limitation on testing on a platform instead of physical device.

https://stackoverflow.com/a/68735254/12124

**Comment by provivek2124** [comment] 2022-03-03 08:23
iPhone devices on Browser Stack does not show the password you are typing in password box. 
Simple Resolution to this issue is:
1) Select Password box.
2) Enter Password by typing(Password box will remain blank when you are typing)
3) Click on Login button.

It will work
