### ISSUE TITLE
Login and Sign Up Popup renders blank on iPhone Browser (after upgrading to 11.12.1)

### ISSUE THREAD

**Issue by ak99372** [auth0/lock#1588] opened 2019-01-11 22:41 UTC
### Description
After upgrading to 11.12.1 (from 11.11.0) the website popup renders blank on some iPhone devices (reproduced on iPhone X iOS11, iOS12) 

**NOTE: This issue does not exist on 11.11.0**

### Environment
* Lock version: 11.12.1
* Browser version: iPhone X
* OS: iOS 11, 12

### Code snippet/reproduce:

```
import { Auth0Lock } from 'auth0-lock';
const lock = new Auth0Lock(Auth0Config.clientId, Auth0Config.domain, {
	allowLogin: true,
	allowSignUp: true,
	allowForgotPassword: true,
	closable: true,
	allowedConnections: null,
	rememberLastLogin: false,
	hashCleanup: false,
	mustAcceptTerms: false,
	defaultADUsernameFromEmailPrefix: false,
	socialButtonStyle: 'small',
	configurationBaseUrl: 'https://cdn.auth0.com'
});

lock.show({
			allowLogin: true,
			allowSignUp: true,
			allowForgotPassword: true,
			initialScreen: 'login'
		});
```

**Comment by crypto-jones** [comment] 2019-01-13 20:39
My team and I are having the exact same issue.

**Comment by luisrudge** [comment] 2019-01-14 15:46
Do you have a specific website I can test? I just tested http://brucke.club and it works on my iPhone XR.

**Comment by crypto-jones** [comment] 2019-01-14 16:04
https://proofd.app
About 30% of the time, nothing will pop up when logging in /signing up on an iOS device.

**Comment by luisrudge** [comment] 2019-01-14 16:10
@crypto-jones @ak99372 are you using angular?

**Comment by luisrudge** [comment] 2019-01-14 16:15
@crypto-jones can you see if this css helps? https://github.com/auth0/angular-lock/issues/38#issuecomment-385995202

```css
.auth0-lock.auth0-lock .auth0-lock-form {
  display: initial !important;
}
```

**Comment by atalebagha** [comment] 2019-02-07 09:13
I'm having this issue on react-native WebView on iOS 12

**Comment by luisrudge** [comment] 2019-02-07 17:14
@atalebagha can you test if the css snippet above fixes your issue?

**Comment by atalebagha** [comment] 2019-02-10 17:23
Yes it fixes the issue.

**Comment by arvidkahl** [comment] 2019-03-30 16:10
Funny enough, switching device orientation does seem to fix it (which I assume is due to the re-render). Advise your users to torn their phones :)

**Comment by arvidkahl** [comment] 2019-03-31 09:55
I guess if you can live with the lack of padding (in lieu of trying to fix it manually with more css), this changed css will target iphones only (using `.auth0-lock-iphone`) and not re-style any desktop version.

```css
.auth0-lock-iphone.auth0-lock .auth0-lock-form {
  display: initial !important;
}
```

**Comment by arvidkahl** [comment] 2019-03-31 10:07
Furthermore, I would like to point out that the fix for this from May 2018 at https://github.com/auth0/lock/pull/1365 was reverted later in https://github.com/auth0/lock/commit/93e4a04eee779efc036caa3915da0975ca01ac48#diff-6e75cf9db4a3c7d943f8603dc182c0e9L314

I am not sure if that was intentional, but even with the latest 11.14.1 lock.js this is what happens more than 50% of the time:

(without the above css addition)
<img width="442" alt="Screenshot 2019-03-31 12 05 26" src="https://user-images.githubusercontent.com/954549/55287754-5c083480-53ad-11e9-88da-6d6815db39de.png">

(with the above css addition)
<img width="407" alt="Screenshot 2019-03-31 12 06 37" src="https://user-images.githubusercontent.com/954549/55287766-80fca780-53ad-11e9-9774-a9d0089e0e13.png">

Simulator, iOS 12.1, iPhone X. Same problem on real device.

**Comment by alacret** [comment] 2019-05-21 21:09
This is still happening in v11.16.0

You can go to:  pex.cobuildlab.com

<img width="1680" alt="Screen Shot 2019-05-21 at 5 08 32 PM" src="https://user-images.githubusercontent.com/918895/58130847-174d8c80-7beb-11e9-99d5-704d9b60295a.png">

**Comment by jasonkim** [comment] 2019-05-31 01:38
A couple things I've discovered while looking at this bug (it's happening to us as well).

1. [Difference between 11.11.0 and 11.12.0 (and what I think is relevant).](https://github.com/auth0/lock/compare/v11.11.0...v11.12.0#diff-6e75cf9db4a3c7d943f8603dc182c0e9R310)

2. Using safari and spoofing my user agent as iOS, I am seeing different results for computed value of display on the div. When div does not have display set explicitly, it renders as `display:block`. When div is set to `display:initial`, it renders as `display:inline`. These were observed using the computed tab.

Based on these, I believe the css treatment for the `auth0-lock-form` div went from `inline` to `block`. The padding was moved from `auth0-lock-content` div to `auth0-lock-form` div, but that has no effect when div is `inline`. That's why the padding is gone in the temp fix.

My fix for this for now is this. (I've found that it also repros without user agent being set to iOS/iphone)

```
.auth0-lock .auth0-lock-form {
  display: initial;
}
.auth0-lock .auth0-lock-content {
  padding: 20px;
}
```

**Comment by vladys-k** [comment] 2019-07-17 14:19
Try to use in the HTML `<head>` tag or within CSS
```
<style>
 .auth0-lock-container {
     height: 90vh !important;
 }
</style>
```

**Comment by luisrudge** [comment] 2019-09-27 01:49
Hi there! I came back to fix this issue but I can't reproduce it anymore with 11.7. Can someone validate that this is fixed in this version and, if you're still having this issue, send me a link to reproduce it?

**Comment by ajmueller** [comment] 2019-09-30 21:49
@luisrudge do you mean 11.17?  I just tested 11.17.2 in an iOS 13 simulator with our AngularJS app and removed our CSS fix.  As you can see, the popup is still rendering blank.

![image](https://user-images.githubusercontent.com/1442179/65919480-4b06a300-e391-11e9-814f-f8a1840e3c26.png)

**Comment by luisrudge** [comment] 2019-10-01 01:46
@ajmueller ok perfect. I tried to run outside of an angular app and couldn't repro. Can you put a simple repro of angular+lock with this issue on github? I'll clone and work based on that. Thanks!

**Comment by ajmueller** [comment] 2019-10-01 19:48
@luisrudge I've [created a repository you can clone](https://github.com/ajmueller/auth0-lock-issue-1588).  I've tested this on Xcode's iOS 13 simulator and it reproduces the error as expected.

A couple notes:
* This is built off of [angular-seed](https://github.com/angular/angular-seed) which has a less than ideal build pipeline, but so it goes when working in the AngularJS world.  This should hopefully have everything you need to work on the issue, however.
* I'm using Node 12 and have added an nvmrc file accordingly.
* You'll need to add an Auth0 Client ID and Domain in [app/services/auth.js](https://github.com/ajmueller/auth0-lock-issue-1588/blob/master/app/services/auth.js#L2) to get this to load.

**Comment by luisrudge** [comment] 2019-10-01 20:24
@ajmueller thank you so much for this! It's perfect. I'll repro and find a way to fix it 🎉

**Closed** 2019-10-28 16:39 UTC
Labels: bug
