### ISSUE TITLE
Seems not to work with webpack

### ISSUE THREAD

**Issue by claudiuandrei** [auth0/lock#121] opened 2015-02-07 23:50 UTC
When trying to use auth0-lock node module with webpack and react I get a bunch of errors

```
Line 1: Unexpected token <
You may need an appropriate loader to handle this file type.
| <div id="a0-lock" class="a0-lock<%= (locals && locals.options.theme) ? ' a0-theme-' + locals.options.theme : ''%>" dir="auto">
|   <div class="a0-signin">
|     <div class="a0-popup <%= (locals && locals.cordova) ? 'a0-cordova' : '' %> <%= (locals && locals.ios) ? 'a0-ios' : '' %>">
 @ ./~/auth0-lock/index.js 18:15-45
```

**Comment by pose** [comment] 2015-02-18 12:54
Hi @claudiuandrei,

Do you have a small project where I can reproduce this?

Thanks in advance,

**Comment by pose** [comment] 2015-02-25 17:00
Duplicate of #54, let's follow up on that issue.

**Closed by pose** 2015-02-25 17:00 UTC
Labels: enhancement
